### ISSUE TITLE
Firmware procedure

### ISSUE THREAD

**Issue by Dozentz** [jaromeyer/mipurifier-esphome#2]
This action leads to the prohibition of reducing the service life of the RFID sticker, in other words, the sticker becomes endless?
Please describe in more detail the procedure for flashing and manipulating in the home assistant

**Comment by jaromeyer** [comment]
Flashing ESPHome on the ESP32 does NOT change anything about the filter life, since that is managed by the other microcontroller. However you can easily reset the filter without even having to modify anything by following [this](https://youtu.be/usiX_J9Yy2o). For installing ESPHome you will have to physically open the purifier to access the UART pads and use a USB-to-serial adapter to flash the ESP32.
